/**
 * Dimension definitions — the 8 neuroscience dimensions available in the quiz.
 */

import type { Dimension } from "./types";

export const DIMENSIONS: Dimension[] = [
  {
    id: "anatomy",
    name: "Neuroanatomy",
    shortName: "Anatomy",
    icon: "",
    description:
      "Identify and locate brain regions by name, structure, and function.",
    color: "--sumi-deep",
    quizTypes: [
      {
        id: "identify",
        dimensionId: "anatomy",
        name: "Identify Region",
        description: "Region is highlighted — name it.",
        answerFormat: "multiple-choice",
        difficulty: "beginner",
        questionCount: 10,
      },
      {
        id: "locate",
        dimensionId: "anatomy",
        name: "Locate Region",
        description: "Name given — click it on the brain.",
        answerFormat: "click-on-brain",
        difficulty: "intermediate",
        questionCount: 10,
      },
    ],
  },
  {
    id: "pathways",
    name: "White Matter Pathways",
    shortName: "Pathways",
    icon: "",
    description: "Trace major white matter tracts connecting brain regions.",
    color: "--ai",
    quizTypes: [
      {
        id: "name-tract",
        dimensionId: "pathways",
        name: "Name the Tract",
        description: "Two regions highlighted — which tract connects them?",
        answerFormat: "multiple-choice",
        difficulty: "intermediate",
        questionCount: 10,
      },
      {
        id: "tract-endpoints",
        dimensionId: "pathways",
        name: "Tract Endpoints",
        description: "Tract highlighted — which regions does it connect?",
        answerFormat: "multiple-choice",
        difficulty: "intermediate",
        questionCount: 10,
      },
      {
        id: "build-circuit",
        dimensionId: "pathways",
        name: "Build a Circuit",
        description: "Sequence structures and tracts in a neural circuit.",
        answerFormat: "ordering",
        difficulty: "advanced",
        questionCount: 8,
      },
    ],
  },
  {
    id: "networks",
    name: "Functional Networks",
    shortName: "Networks",
    icon: "",
    description: "Map the brain's large-scale functional networks.",
    color: "--murasaki",
    quizTypes: [
      {
        id: "region-to-network",
        dimensionId: "networks",
        name: "Region to Network",
        description: "Region highlighted — which network does it belong to?",
        answerFormat: "multiple-choice",
        difficulty: "intermediate",
        questionCount: 10,
      },
      {
        id: "network-disruption",
        dimensionId: "networks",
        name: "Network Disruption",
        description: "Condition described — which network is disrupted?",
        answerFormat: "multiple-choice",
        difficulty: "advanced",
        questionCount: 10,
      },
      {
        id: "network-scenario",
        dimensionId: "networks",
        name: "Network Activity",
        description: "Mental activity described — which network is active?",
        answerFormat: "multiple-choice",
        difficulty: "beginner",
        questionCount: 10,
      },
    ],
  },
  {
    id: "neurotransmitters",
    name: "Neurotransmitter Systems",
    shortName: "NTs",
    icon: "",
    description: "Trace neurotransmitter pathways and their pharmacology.",
    color: "--moegi",
    quizTypes: [
      {
        id: "nt-source",
        dimensionId: "neurotransmitters",
        name: "NT Source",
        description: "Name the system — where are the cell bodies?",
        answerFormat: "click-on-brain",
        difficulty: "intermediate",
        questionCount: 8,
      },
      {
        id: "nt-affected",
        dimensionId: "neurotransmitters",
        name: "Which NT?",
        description: "Clinical vignette — which neurotransmitter system?",
        answerFormat: "multiple-choice",
        difficulty: "intermediate",
        questionCount: 10,
      },
      {
        id: "pharma-bridge",
        dimensionId: "neurotransmitters",
        name: "Pharma Bridge",
        description: "Drug name — which system does it act on?",
        answerFormat: "multiple-choice",
        difficulty: "advanced",
        questionCount: 10,
      },
      {
        id: "disease-circuit",
        dimensionId: "neurotransmitters",
        name: "Disease Circuit",
        description: "Disease — select ALL affected NT systems.",
        answerFormat: "multi-select",
        difficulty: "advanced",
        questionCount: 8,
      },
    ],
  },
  {
    id: "clinical",
    name: "Clinical Neuroscience",
    shortName: "Clinical",
    icon: "",
    description:
      "Localize lesions, identify syndromes, and trace vascular territories.",
    color: "--beni",
    quizTypes: [
      {
        id: "lesion-deficit",
        dimensionId: "clinical",
        name: "Lesion Localization",
        description: "Symptoms described — where is the lesion?",
        answerFormat: "click-on-brain",
        difficulty: "intermediate",
        questionCount: 10,
      },
      {
        id: "deficit-from-region",
        dimensionId: "clinical",
        name: "Predict the Deficit",
        description: "Region highlighted — what deficit would occur?",
        answerFormat: "multiple-choice",
        difficulty: "intermediate",
        questionCount: 10,
      },
      {
        id: "which-artery",
        dimensionId: "clinical",
        name: "Which Artery?",
        description: "Deficits described — which vascular territory?",
        answerFormat: "multiple-choice",
        difficulty: "advanced",
        questionCount: 10,
      },
      {
        id: "name-syndrome",
        dimensionId: "clinical",
        name: "Name the Syndrome",
        description: "Symptom cluster — identify the syndrome.",
        answerFormat: "multiple-choice",
        difficulty: "advanced",
        questionCount: 10,
      },
      {
        id: "case-vignette",
        dimensionId: "clinical",
        name: "Case Study",
        description: "Full clinical case — localize and identify.",
        answerFormat: "multiple-choice",
        difficulty: "advanced",
        questionCount: 8,
      },
      {
        id: "visual-field",
        dimensionId: "clinical",
        name: "Visual Field Defects",
        description: "Visual field pattern — where is the lesion?",
        answerFormat: "multiple-choice",
        difficulty: "advanced",
        questionCount: 8,
      },
    ],
  },
  {
    id: "developmental",
    name: "Developmental Neuroscience",
    shortName: "Development",
    icon: "",
    description: "Trace brain development from embryo to adult.",
    color: "--kitsune",
    quizTypes: [
      {
        id: "vesicle-origin",
        dimensionId: "developmental",
        name: "Vesicle Origin",
        description: "Structure — which embryological vesicle?",
        answerFormat: "multiple-choice",
        difficulty: "intermediate",
        questionCount: 10,
      },
      {
        id: "myelination-order",
        dimensionId: "developmental",
        name: "Myelination Order",
        description: "Sort structures by myelination timing.",
        answerFormat: "ordering",
        difficulty: "advanced",
        questionCount: 8,
      },
      {
        id: "evolution-order",
        dimensionId: "developmental",
        name: "Evolutionary Timeline",
        description: "Sort structures by evolutionary appearance.",
        answerFormat: "ordering",
        difficulty: "advanced",
        questionCount: 8,
      },
    ],
  },
  {
    id: "neuroimaging",
    name: "Neuroimaging & Atlases",
    shortName: "Imaging",
    icon: "",
    description: "Match imaging modalities, Brodmann areas, and atlas systems.",
    color: "--ai",
    quizTypes: [
      {
        id: "modality-selection",
        dimensionId: "neuroimaging",
        name: "Choose the Modality",
        description: "Research question — which imaging technique?",
        answerFormat: "multiple-choice",
        difficulty: "intermediate",
        questionCount: 10,
      },
      {
        id: "brodmann-match",
        dimensionId: "neuroimaging",
        name: "Brodmann Match",
        description: "Brodmann area number — what function?",
        answerFormat: "multiple-choice",
        difficulty: "intermediate",
        questionCount: 10,
      },
      {
        id: "resolution-ranking",
        dimensionId: "neuroimaging",
        name: "Resolution Ranking",
        description: "Sort modalities by resolution.",
        answerFormat: "ordering",
        difficulty: "advanced",
        questionCount: 6,
      },
    ],
  },
  {
    id: "cellular",
    name: "Cellular Architecture",
    shortName: "Cellular",
    icon: "",
    description:
      "Identify cell types, cortical layers, and receptor distributions.",
    color: "--moegi",
    quizTypes: [
      {
        id: "cell-type",
        dimensionId: "cellular",
        name: "Signature Cell",
        description: "Region — what's the unique cell type?",
        answerFormat: "multiple-choice",
        difficulty: "intermediate",
        questionCount: 10,
      },
      {
        id: "cortical-layer",
        dimensionId: "cellular",
        name: "Cortical Layer",
        description: "Function — which layer?",
        answerFormat: "multiple-choice",
        difficulty: "advanced",
        questionCount: 10,
      },
      {
        id: "receptor-distribution",
        dimensionId: "cellular",
        name: "Receptor Map",
        description: "Region — dominant receptor type?",
        answerFormat: "multiple-choice",
        difficulty: "advanced",
        questionCount: 10,
      },
      {
        id: "hippocampal-circuit",
        dimensionId: "cellular",
        name: "Hippocampal Circuit",
        description: "Subfield — what are its connections?",
        answerFormat: "multiple-choice",
        difficulty: "advanced",
        questionCount: 8,
      },
    ],
  },
];

export function getDimension(id: string): Dimension | undefined {
  return DIMENSIONS.find((d) => d.id === id);
}

export function getQuizType(dimensionId: string, quizTypeId: string) {
  const dim = getDimension(dimensionId);
  return dim?.quizTypes.find((qt) => qt.id === quizTypeId);
}
