import type { Metadata } from "next";
import { RegionShot } from "@/components/render/RegionShot";

/**
 * Internal figure-rendering surface: /render?region=<slug>.
 *
 * Kept out of the sitemap and out of the index. It exists so figure images can
 * be captured from the same meshes the quiz uses, rather than drawn by hand or
 * generated by an image model that does not know where the thalamus is.
 */
export const metadata: Metadata = {
  title: "Region render",
  robots: { index: false, follow: false },
};

export default function RenderPage() {
  return <RegionShot />;
}
